name: Go

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: build
        run: go build -v ./...
      - name: test
        run: go test -v ./...